# Debug等级
debug: 0


# UUID相关
#=================================
uuid:
  # 是否开启正版模式，不设置时默认为false
  # 注意：当启用正版模式时，玩家的UUID将通过mojangapi获取，请保证你的服务器能访问外网
  #       当禁用正版模式时，玩家的UUID是自动生成的
  # 警告：切换正版模式的启用/禁用状态可能导致数据混乱，请清空插件数据后再启用/禁用正版模式！！！
  online-mode: false
  # UUID的缓存时间(单位为毫秒值)，不设置时默认为一天(即86400000)
  # 注：若缓存时间为负数则相当于缓存时间无穷大
  # 提示：当禁用正版模式时，缓存时间建议设为-1
  cache-time: -1 
# 数据库配置
#=================================
database:
  # 数据库类型
  # 当前支持的数据库类型：
  # SQLite，MySQL
  type: SQLite
  
  # 数据库表前缀
  table-prefix: eg_
  
  # 与数据库类型相关的配置
  #===============================
  SQLite: # SQLite数据库相关的配置
    # 数据库路径(服务器根目录的相对路径)
    path: data/epicguild.db
  #-------------------------------
  MySQL: # MySQL数据库相关的配置
    # 数据库主机
    host: localhost
    # 数据库端口
    port: 3306
    # 数据库名
    database-name: epicguild
    # 用户名
    user: root
    # 密码
    password: ''
  #===============================
  