name: EpicGuild
main: org.yunshanmc.epicguild.EpicGuildPlugin
version: 1.3.1.2
softdepend: [Vault,Multiverse-Core,RPG_Items,MoreItems,DeluxeChat]
commands:
  epicguild:
    aliases: [eg, guild, g]
    description: 插件命令
    usage: 插件加载错误，请联系OP查看后台报错
  epicguildadmin:
    aliases: [egadmin, guildadmin, gadmin]
    description: 插件管理命令
    usage: 插件加载错误，请联系OP查看后台报错
permissions:
# -------------------------------------------- #
# 管理权限
# -------------------------------------------- #
  epicguild.admin: {default: false}
# -------------------------------------------- #
# 使用权限
# -------------------------------------------- #
  epicguild.create: {default: false}
  epicguild.use: {default: true}
# -------------------------------------------- #
# 所有权限
# -------------------------------------------- #
  epicguild.*:
    default: op
    children:
      epicguild.use: true
      epicguild.create: true
      epicguild.admin: true