name: EpicGuild
main: org.yunshanmc.epicguild.EpicGuildPlugin
version: 1.3.1.2
depend: [YCL]
softdepend: [Vault,Multiverse-Core,RPG_Items,MoreItems,DeluxeChat]
commands:
  epicguild:
    aliases: [eg, guild, g]
    description: 插件命令
    usage: '§e[§aEpicGuild§e]§c插件加载失败！请查看加载时的后台报错！'
  epicguildadmin:
    aliases: [egadmin, guildadmin, gadmin]
    description: 插件管理命令
    usage: '§e[§aEpicGuild§e]§c插件加载失败！请查看加载时的后台报错！'
permissions:
# -------------------------------------------- #
# 管理权限
# -------------------------------------------- #
  epicguild.admin:
    default: false
    children:
      epicguild.use: true
      epicguild.create: true
      epicguild.help.refreshCache: true
# -------------------------------------------- #
# 使用权限
# -------------------------------------------- #
  epicguild.create: {default: false}
  epicguild.use: {default: true}
  epicguild.help.refreshCache: {default: false}
# -------------------------------------------- #
# 所有权限
# -------------------------------------------- #
  epicguild.*:
    default: op
    children:
      epicguild.use: true
      epicguild.create: true
      epicguild.admin: true
      epicguild.help.refreshCache: true